<?php

$bonus_cards = [
    'attack' => [
        'name' => clienttranslate('Attack'),
        'rank' => 0,
        'effect' => 'attack',
        'targets' => 1,
        'damage' => 1,
        'range' => [0, 1],
        'range_metric' => 'chebyshev',
        'cooldown' => 1,
        'free_triggers' => [],
        'upgrades_to' => null,
    ],
    'strike' => [
        'name' => clienttranslate('Strike'),
        'rank' => 0,
        'effect' => 'attack',
        'targets' => 1,
        'damage' => 2,
        'range' => [0, 1],
        'range_metric' => 'orthogonal',
        'cooldown' => 1,
        'free_triggers' => [],
        'upgrades_to' => null,
    ],
    'dash_1' => [
        'name' => clienttranslate('Dash'),
        'rank' => 1,
        'effect' => 'dash',
        'distance' => [1, 2],
        'range_metric' => 'orthogonal',
        'cooldown' => 2,
        'free_triggers' => ['afterCardPlayed'],
        'upgrades_to' => 'dash_2',
    ],
    'dash_2' => [
        'name' => clienttranslate('Dash'),
        'rank' => 2,
        'effect' => 'dash',
        'distance' => [1, 3],
        'range_metric' => 'orthogonal',
        'cooldown' => 2,
        'free_triggers' => ['afterCardPlayed'],
        'upgrades_to' => 'dash_3',
    ],
    'dash_3' => [
        'name' => clienttranslate('Dash'),
        'rank' => 3,
        'effect' => 'dash',
        'distance' => [1, 3],
        'range_metric' => 'orthogonal',
        'cooldown' => 1,
        'free_triggers' => ['afterCardPlayed'],
        'upgrades_to' => null,
    ],
    'vortex' => [
        'name' => clienttranslate('Vortex'),
        'rank' => 1,
        'effect' => 'pull',
        'targets' => 2,
        'range' => [0, 2],
        'range_metric' => 'chebyshev',
        'target_range_from_selected_tile' => [1, 1],
        'pull_distance' => 1,
        'cooldown' => 2,
        'free_triggers' => [],
        'upgrades_to' => 'vortex_2',
    ],
    'vortex_2' => [
        'name' => clienttranslate('Vortex'),
        'rank' => 2,
        'effect' => 'pull',
        'targets' => 3,
        'range' => [0, 2],
        'range_metric' => 'chebyshev',
        'target_range_from_selected_tile' => [1, 1],
        'pull_distance' => 1,
        'cooldown' => 2,
        'free_triggers' => [],
        'upgrades_to' => 'vortex_3',
    ],
    'vortex_3' => [
        'name' => clienttranslate('Vortex'),
        'rank' => 3,
        'effect' => 'pull',
        'targets' => 4,
        'range' => [0, 2],
        'range_metric' => 'chebyshev',
        'target_range_from_selected_tile' => [1, 1],
        'pull_distance' => 1,
        'cooldown' => 2,
        'free_triggers' => [],
        'upgrades_to' => null,
    ],
    'quick-strike_1' => [
        'name' => clienttranslate('Quick Strike'),
        'rank' => 1,
        'effect' => 'attack',
        'targets' => 2,
        'damage' => 1,
        'range' => [0, 1],
        'range_metric' => 'chebyshev',
        'cooldown' => 2,
        'free_triggers' => ['afterMove'],
        'upgrades_to' => 'quick-strike_2',
    ],
    'quick-strike_2' => [
        'name' => clienttranslate('Quick Strike'),
        'rank' => 2,
        'effect' => 'attack',
        'targets' => 3,
        'damage' => 1,
        'range' => [0, 1],
        'range_metric' => 'chebyshev',
        'cooldown' => 2,
        'free_triggers' => ['afterMove'],
        'upgrades_to' => 'quick-strike_3',
    ],
    'quick-strike_3' => [
        'name' => clienttranslate('Quick Strike'),
        'rank' => 3,
        'effect' => 'attack',
        'targets' => 4,
        'damage' => 1,
        'range' => [0, 1],
        'range_metric' => 'chebyshev',
        'cooldown' => 2,
        'free_triggers' => ['afterMove'],
        'upgrades_to' => null,
    ],
    'quick-shot_1' => [
        'name' => clienttranslate('Quick Shot'),
        'rank' => 1,
        'effect' => 'attack',
        'targets' => 2,
        'damage' => 1,
        'range' => [2, 3],
        'range_metric' => 'chebyshev',
        'cooldown' => 2,
        'free_triggers' => ['afterMove'],
        'upgrades_to' => 'quick-shot_2',
    ],
    'quick-shot_2' => [
        'name' => clienttranslate('Quick Shot'),
        'rank' => 2,
        'effect' => 'attack',
        'targets' => 3,
        'damage' => 1,
        'range' => [2, 3],
        'range_metric' => 'chebyshev',
        'cooldown' => 2,
        'free_triggers' => ['afterMove'],
        'upgrades_to' => 'quick-shot_3',
    ],
    'quick-shot_3' => [
        'name' => clienttranslate('Quick Shot'),
        'rank' => 3,
        'effect' => 'attack',
        'targets' => 4,
        'damage' => 1,
        'range' => [2, 4],
        'range_metric' => 'chebyshev',
        'cooldown' => 2,
        'free_triggers' => ['afterMove'],
        'upgrades_to' => null,
    ],
];

return $bonus_cards;
