<?php

const HNS_EASY_HEALTH = 20;
const HNS_DEFAULT_HEALTH = 10;
const HNS_HARD_HEALTH = 5;
const HNS_HARDCORE_HEALTH = 1;
const HNS_SOLO_ACTION_POINTS = 2;
const HNS_MULTIPLAYER_ACTION_POINTS = 1;
const HNS_DEFAULT_ACTION_POINTS = HNS_SOLO_ACTION_POINTS;
const HNS_FIRST_LEVEL = 1;
const HNS_BOSS_LEVEL = 8;
const HNS_SCENARIO_DUNGEON = 1;
const HNS_SCENARIO_BOSS_FIGHT = 2;
const HNS_DIFFICULTY_EASY = 1;
const HNS_DIFFICULTY_NORMAL = 2;
const HNS_DIFFICULTY_HARD = 3;
const HNS_DIFFICULTY_HARDCORE = 4;
