<?php

const HNS_DEFAULT_HEALTH = 10;
const HNS_SOLO_ACTION_POINTS = 2;
const HNS_MULTIPLAYER_ACTION_POINTS = 1;
const HNS_DEFAULT_ACTION_POINTS = HNS_SOLO_ACTION_POINTS;
const HNS_FIRST_LEVEL = 1;
const HNS_BOSS_LEVEL = 8;
const HNS_DIFFICULTY_NORMAL = 1;
const HNS_DIFFICULTY_BOSS_FIGHT = 2;
const HNS_BOSS_FIGHT_HEALTH = 100;
