<?php

// Placeholder material. Replace or generate from src/resources/bestiary.csv later.
$monsters = [
    1 => [
        'name' => clienttranslate('Goblins'),
        'level' => 1,
        'health' => 1,
        'spawn_count' => 2,
        'move' => 1,
        'move_metric' => 'orthogonal',
        'range' => 1,
        'range_metric' => 'orthogonal',
        'damage' => 1,
        'size' => 'small',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    2 => [
        'name' => clienttranslate('Slimes'),
        'level' => 1,
        'health' => 2,
        'spawn_count' => 1,
        'move' => 2,
        'move_metric' => 'chebyshev',
        'range' => 1,
        'range_metric' => 'orthogonal',
        'damage' => 0,
        'effect' => 'slime',
        'size' => 'small',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    3 => [
        'name' => clienttranslate('Evil Eye'),
        'level' => 1,
        'health' => 1,
        'spawn_count' => 1,
        'move' => 0,
        'move_metric' => 'orthogonal',
        'range' => 3,
        'range_metric' => 'chebyshev',
        'damage' => 1,
        'size' => 'small',
        'can_attack' => true,
        'can_move' => false,
        'can_attack_and_move' => false,
    ],
    4 => [
        'name' => clienttranslate('Kamikaze'),
        'level' => 1,
        'health' => 1,
        'spawn_count' => 1,
        'move' => 1,
        'move_metric' => 'chebyshev',
        'range' => 1,
        'range_metric' => 'orthogonal',
        'damage' => 2,
        'effect' => 'explode',
        'on_death' => 'explode',
        'size' => 'small',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    5 => [
        'name' => clienttranslate('Wizard'),
        'level' => 1,
        'health' => 2,
        'spawn_count' => 1,
        'move' => 1,
        'move_metric' => 'orthogonal',
        'range' => 4,
        'min_range' => 2,
        'range_metric' => 'chebyshev',
        'damage' => 1,
        'size' => 'small',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    6 => [
        'name' => clienttranslate('Bomber'),
        'level' => 1,
        'health' => 3,
        'spawn_count' => 1,
        'move' => 1,
        'move_metric' => 'orthogonal',
        'range' => 3,
        'min_range' => 2,
        'range_metric' => 'chebyshev',
        'damage' => 1,
        'size' => 'small',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    7 => [
        'name' => clienttranslate('Orc'),
        'level' => 1,
        'health' => 4,
        'spawn_count' => 1,
        'move' => 1,
        'move_metric' => 'orthogonal',
        'range' => 1,
        'range_metric' => 'front_arc',
        'damage' => 2,
        'effect' => 'front_arc',
        'size' => 'big',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    8 => [
        'name' => clienttranslate('Pig Rider'),
        'level' => 1,
        'health' => 4,
        'spawn_count' => 1,
        'move' => 1,
        'move_metric' => 'orthogonal',
        'range' => 1,
        'range_metric' => 'orthogonal',
        'damage' => 1,
        'effect' => 'charge',
        'size' => 'big',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => false,
    ],
    9 => [
        'name' => clienttranslate('Wolf Rider'),
        'level' => 1,
        'health' => 3,
        'spawn_count' => 1,
        'move' => 1,
        'move_metric' => 'orthogonal',
        'range' => 0,
        'damage' => 0,
        'effect' => 'summon_then_flee',
        'summon_monster_id' => 1,
        'summon_count' => 1,
        'size' => 'big',
        'can_attack' => true,
        'can_move' => true,
        'can_attack_and_move' => true,
    ],

];

return $monsters;
